[workspace]
resolver = "2"
members = [
    "01-introduction/hello_world",
    "02-guess_game/guess_game",
    "03-general_concepts/branch",
    "03-general_concepts/compound",
    "03-general_concepts/variables",
]
